bstract class Race {
    String name
    int hp
}
abstract class Terran extends Race
abstract class Zerg extends Race implements Recoverable
abstract class Protoss extends Race implements Recoverable {
    int shield
}

interface Unit {
    void move()
}
interface Bionic
interface Mechanic
interface Building
interface Healable
interface Repairable
interface Recoverable {
    void recover()
}

interface BionicUnit implements Unit, Bionic, Healable
interface MechanicUnit implements Unit, Mechanic, Repairable
interface BionicBuilding implements Building, Bionic

class Marine extends Terran implements BionicUnit
class Medic extends Terran implements BionicUnit {
    void heal(Healable)
}
class SCV extends Terran implements MechanicUnit, Healable {
    int mine(Resource)
    void repair(Repairable)
}
class Vulture extends Terran implements MechanicUnit
class Tank extends Terran implements MechanicUnit

class Zealor extends Protoss implements BionicUnit
class Dragun extends Protoss implements MechanicUnit

class Squadron {
    static final maxCount = 12
    List<Unit> members;

    void add(Unit)
}